name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        cd implementations/python
        pip install -e .
    
    - name: Build package
      run: |
        cd implementations/python
        python -m build
    
    - name: Check package
      run: |
        cd implementations/python
        twine check dist/*
    
    - name: Generate changelog
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
        # Generate changelog (simple approach)
        echo "# Release Notes for v$VERSION" > RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "## Changes" >> RELEASE_NOTES.md
        
        # Get commits since last tag
        LAST_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
        if [ -n "$LAST_TAG" ]; then
          git log --pretty=format:"- %s" $LAST_TAG..HEAD >> RELEASE_NOTES.md
        else
          git log --pretty=format:"- %s" >> RELEASE_NOTES.md
        fi
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ env.VERSION }}
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
    
    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ env.VERSION }}
        path: implementations/python/dist/
    
    # Uncomment when ready to publish to PyPI
    # - name: Publish to PyPI
    #   env:
    #     TWINE_USERNAME: __token__
    #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    #   run: |
    #     twine upload dist/*
